const data = [
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Fresh Onions",
        subtitle: "Vegetables",
        imageUrl: "https://www.foodqualityandsafety.com/wp-content/uploads/2018/08/FQU_eUpdate_0925_onions.jpg",
        description: "Very good, will make you cry",
        phonenumber: "861234567",
        price: "0.50",
        seller: "Galyna29",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
    {
        title: "Cucumbers from my garden",
        subtitle: "Vegetables",
        imageUrl: "https://www.shethepeople.tv/wp-content/uploads/2019/05/cucumber-e1558166231577.jpg",
        description: "I picked these myself. They're grown with love and without any chemicals",
        phonenumber: "861234567",
        price: "0.89",
        seller: "Adam12",
    },
]

export default data